- name: Create a jenkins pipeline job which trigger by token using xml file
  community.general.jenkins_job:
    config: "{{ lookup('template', 'pipeline.xml') }}"
    name: test
    token: 114110016c850567cad435985c90415a9e
    url: http://172.31.8.157:8080
    user: admin
  loop :
    - { TokenName : 'cart', RepoName : 'cart' }

# use token instead of password


