- name: Create a jenkins pipeline job which trigger by token using xml file
  community.general.jenkins_job:
    config: "{{ lookup('template', 'templates/pipeline.xml') }}"
    name: test
    password: admin
    url: http://172.31.8.157:8080
    user: admin
  loop:
    - { TokenName: 'cart', RepoName: 'cart' }
