- name: Create a jenkins pipeline job which trigger by token using xml file
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/pipeline.xml') }}"
    name: test
    password: admin
    url: http://172.31.2.60:8080
    user: admin
  loop :
    - { TokenName : 'cart', RepoName : 'cart' }
