#- name: template
#  template:
#    src : pipeline.xml
#    dest: /tmp/pipeline.xml
#  loop :
#  - { TokenName : 'cart', RepoName : 'cart' }

#  first copy template file then us it for job creation & instead of password use token

- name: Create a jenkins pipeline job which trigger by token using xml file
  community.general.jenkins_job:
    config: "{{ lookup('template', 'pipeline.xml') }}"
    name: test
    password: 114110016c850567cad435985c90415a9e
    url: http://172.31.8.157:8080
    user: admin
  loop :
    - { TokenName : 'cart', RepoName : 'cart' }




