- name: template
  template:
    src : pipeline.xml
    dest: /tmp/pipeline.xml
  loop :
  - { TokenName : 'cart', RepoName : 'cart' }


- name: Create a jenkins pipeline job which trigger by token using xml file
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/pipeline.xml') }}"
    name: test
    password: admin
    url: http://3.235.68.2:8080
    user: admin

