FOLDER:
  - {FolderName: 'CI-Pipeline', Description: 'CI Pipeline jobs for all roboshop component', DisplayName: 'CI-Pipeline'}

PIPELINES:
  - { TokenName : 'cart', RepoName : 'cart', JobName: 'cart', FolderName: 'CI-Pipeline/' }
  - { TokenName : 'cart', RepoName : 'cart', JobName: 'cart', FolderName: 'CI-Pipeline/' }
  - { TokenName : 'cart', RepoName : 'cart', JobName: 'cart', FolderName: 'CI-Pipeline/' }
  - { TokenName : 'cart', RepoName : 'cart', JobName: 'cart', FolderName: 'CI-Pipeline/' }
  - { TokenName : 'cart', RepoName : 'cart', JobName: 'cart', FolderName: 'CI-Pipeline/' }
  - { TokenName : 'cart', RepoName : 'cart', JobName: 'cart', FolderName: 'CI-Pipeline/' }





